default-bindings start

# Playback & Speed
SPACE       cycle pause
.           frame-step
,           frame-back-step
[           add speed -0.1
]           add speed  0.1
{           add speed -0.5
}           add speed  0.5

# Seeking & Timeline
j           seek -5   exact
k           seek  5   exact
J           seek -10  exact
K           seek  10  exact

# Playlist & Chapters
n           playlist-next
N           playlist-prev
h           add chapter -1
l           add chapter  1

# Audio
m           cycle mute
,           add volume -5
.           add volume  5

# Video & Window Management
f           cycle fullscreen
ESC         set fullscreen no

# Video zoom and pan
z           add video-zoom  0.1
Z           add video-zoom -0.1
UP          add video-pan-y  0.05
DOWN        add video-pan-y -0.05
LEFT        add video-pan-x  0.05
RIGHT       add video-pan-x -0.05
BS          set video-zoom 0; set video-pan-x 0; set video-pan-y 0 # Backspace to reset

# Subtitles
c           cycle sub-visibility
TAB         cycle sub
SHIFT+TAB   cycle sub down

# Screenshot
s           screenshot
S           screenshot video

# On-Screen-Display
o           show-progress

# Audio and Sub Delay
g           ignore              # Unbind 'g' so it acts as our sequential prefix
g-a         add audio-delay  0.1
g-A         add audio-delay -0.1  # 'A' is Shift+a
g-s         add sub-delay    0.1
g-S         add sub-delay   -0.1

# Sub Positioning and Scaling
g           ignore
g-k         add sub-pos -1        # Move subs up
g-j         add sub-pos  1        # Move subs down
g-K         add sub-scale  0.1    # Increase sub size
g-J         add sub-scale -0.1    # Decrease sub size
