hl.on("hyprland.start", function ()
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("~/.config/hypr/scripts/wallpaper.sh start")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprsunset")
  hl.exec_cmd("clipse -listen")
  hl.exec_cmd("waybar")
  hl.exec_cmd("mako")
  hl.exec_cmd("emote")
  hl.exec_cmd("eww daemon")
  hl.exec_cmd("eww open-many date-day-window-main date-day-window-external")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("xhost +si:localuser:root")
end)
