hl.on("hyprland.start", function()
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("~/.config/hypr/scripts/wallpaper.sh start")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprsunset")
  hl.exec_cmd("clipse -listen")
  hl.exec_cmd("qs")
  hl.exec_cmd("swaync")
  hl.exec_cmd("emote")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("xhost +si:localuser:root")
end)
